[window_mode]
width = 800.0
height = 600.0
maximized = false
fullscreen_type = "Windowed"
borderless = false
min_width = 0.0
min_height = 0.0
max_width = 0.0
max_height = 0.0
resizable = true

[window_setup]
title = "batufo"
samples = "Zero"
vsync = true
icon = "/icons/app-icon.png"
srgb = true

[backend]
type = "OpenGL"
major = 3
minor = 2

[modules]
gamepad = false
audio = true
